# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GEELY_ESCL_GP12_Ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(480, 770)
        MainWindow.setMinimumSize(QtCore.QSize(480, 770))
        MainWindow.setMaximumSize(QtCore.QSize(480, 770))
        MainWindow.setBaseSize(QtCore.QSize(800, 480))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Image/Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AnimatedDocks)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.projectname = QtGui.QPushButton(self.centralWidget)
        self.projectname.setEnabled(False)
        self.projectname.setGeometry(QtCore.QRect(0, 730, 481, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.projectname.setFont(font)
        self.projectname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.projectname.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"gridline-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.projectname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.projectname.setDefault(False)
        self.projectname.setObjectName(_fromUtf8("projectname"))
        self.teststart = QtGui.QPushButton(self.centralWidget)
        self.teststart.setGeometry(QtCore.QRect(10, 659, 461, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.teststart.setFont(font)
        self.teststart.setStyleSheet("QPushButton{"

                                     "color:rgb(233, 236, 243);"

                                     "min-height:20;"

                                     "border-style:solid;"

                                     "border-top-left-radius:2px;"

                                     "border-top-right-radius:2px;"

                                     "background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 rgb(226,236,241),"
                                     "stop: 0.3 rgb(33,184,150),"
                                     "stop: 1 rgb(29,170,140));"

                                     "border:1px;"
                                     "border-radius:5px;padding:2px 4px;"

                                     "}"

                                     "QPushButton:hover{"

                                     "color:rgb(233, 236, 243);"

                                     "min-height:20;"

                                     "border-style:solid;"

                                     "border-top-left-radius:2px;"
                                     "background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 rgb(226,236,241),"
                                     "stop: 0.3 rgb(37,189,252),"
                                     "stop: 1 rgb(32,170,240));"
                                     "border:1px;"
                                     "border-radius:5px;padding:2px 4px;"

                                     "}"

                                     "QPushButton:pressed{"

                                     "background-color:rgba(100,255,100,100);"

                                     "border-color:rgba(255,255,255,200);"

                                     "color:rgba(0,0,0,200);"

                                     "}")
        self.teststart.setObjectName(_fromUtf8("teststart"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 481, 731))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(153, 180, 209);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(310, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("font: italic 8pt \"Arial\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.model_select = QtGui.QComboBox(self.frame)
        self.model_select.setGeometry(QtCore.QRect(310, 30, 155, 21))
        self.model_select.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";"))
        self.model_select.setObjectName(_fromUtf8("model_select"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(310, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tableWidget = QtGui.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 461, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(False)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(9, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(280)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(250)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(21)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(390, 100, 89, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 540, 101, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(152, 152, 152); "))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(120, 540, 351, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("background-color: rgb(152, 152, 152); "))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.result_txt_line = QtGui.QLineEdit(self.frame)
        self.result_txt_line.setEnabled(False)
        self.result_txt_line.setGeometry(QtCore.QRect(10, 500, 461, 31))
        self.result_txt_line.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 20pt \"Arial\";"))
        self.result_txt_line.setAlignment(QtCore.Qt.AlignCenter)
        self.result_txt_line.setObjectName(_fromUtf8("result_txt_line"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 480, 54, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_22 = QtGui.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setPixmap(QtGui.QPixmap(_fromUtf8("Image/BCS_logo.png")))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 240, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(310, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 121, 121))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("Image/ESCL_GEELY.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.side_select = QtGui.QComboBox(self.frame)
        self.side_select.setGeometry(QtCore.QRect(310, 160, 155, 21))
        self.side_select.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";"))
        self.side_select.setObjectName(_fromUtf8("side_select"))
        self.side_select.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(310, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.frame.raise_()
        self.projectname.raise_()
        self.teststart.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setMinimumSize(QtCore.QSize(0, 0))
        self.menuBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuBar.setAutoFillBackground(False)
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuFile.sizePolicy().hasHeightForWidth())
        self.menuFile.setSizePolicy(sizePolicy)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuConfig = QtGui.QMenu(self.menuBar)
        self.menuConfig.setObjectName(_fromUtf8("menuConfig"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionDisable_IDLE_Check_Display = QtGui.QAction(MainWindow)
        self.actionDisable_IDLE_Check_Display.setCheckable(True)
        self.actionDisable_IDLE_Check_Display.setObjectName(_fromUtf8("actionDisable_IDLE_Check_Display"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuConfig.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.model_select, self.projectname)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PORTABLE TESTER", None))
        self.projectname.setText(_translate("MainWindow", "ZLE Electronics(Suzhou) Co.,Ltd           TEL : +86-512-66185018  ", None))
        self.teststart.setText(_translate("MainWindow", "START", None))
        self.label_4.setText(_translate("MainWindow", "Test Mode:", None))
        self.label_9.setText(_translate("MainWindow", "Model:", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "F180:  Boot Software Identification", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "F18C:  ECU Serial Number", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "F193:  System Supplier ECU HW Version Number", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "F195:  System Supplier ECU SW Version Number", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "F187:  Geely Spare Part Number", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "F18A:  System Supplier Identifier", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "F18B:  ECU Manufacturing Date", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7109:  ESCL_Learning_Status", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "7107:  ESCL_Steering Lock Status", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "新建行", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建列", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "F180:  Boot Software Identification", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "F18C:  ECU Serial Number", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "F193:  System Supplier ECU HW Version Number", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "F195:  System Supplier ECU SW Version Number", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "F187:  Geely Spare Part Number", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "F18A:  System Supplier Identifier", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "F18B:  ECU Manufacturing Date", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "7109:  ESCL_Learning_Status", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "7107:  ESCL_Steering Lock Status", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "0279：ESCL_Message_Info", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "GEELY ESCL", None))
        self.radioButton.setText(_translate("MainWindow", "Automatic", None))
        self.pushButton_2.setText(_translate("MainWindow", "CLEAR-DTC", None))
        self.pushButton.setText(_translate("MainWindow", "LOCK/UNLOCK", None))
        self.label_7.setText(_translate("MainWindow", "Result:", None))
        self.label.setText(_translate("MainWindow", "Diagnostic data:", None))
        self.radioButton_2.setText(_translate("MainWindow", "Manual", None))
        self.side_select.setItemText(0, _translate("MainWindow", "GEELY", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuConfig.setTitle(_translate("MainWindow", "Config", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.actionDisable_IDLE_Check_Display.setText(_translate("MainWindow", "Disable IDLE Check Display", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))

